services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:${KAFKA_PORT}
    networks:
      - kafka-network
  
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PWD}
    ports:
      - "5432:5432"
    networks:
      - kafka-network
  
  server:
    build:
      dockerfile: Dockerfile
      context: ./
    depends_on:
      - kafka
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: go run .
    develop:
      watch:
      - action: sync+restart
        path: ./
        target: /app
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge